### ISSUE TITLE
Discord Channel Restriction Update Request

### ISSUE THREAD

**Issue by almost2late** [jstanleyf1985/ReplikaDiscordInterface#8]
Hey, Stanley, first of all, thank you for this scatchy tool. 

I faced this Issue too, with Double Messages, but a simply restart helps.. It happens, when you more times click on the Start Interface Button. - Just as mentioned.

 I write you because this field, on the Configuration page,  for the Discord channel restriction for limit in which channel the AI can communicate.
 
I wont use the @mention option because at a longer discussion it can be really annoying, tipping the name of the bot everytime.

So the question is, couldnt you make this filed so, that it ables to put more channels at the same time, separated with any characters? Like: " Room1 | Room2 ; Room3  

 Thnaks and Regards

**Comment by jstanleyf1985** [comment]
I’ll check into that. I thought about adding that when I started the project, unfortunately I haven’t been actively working on this project since it came out. When I update the software I’ll see if I can add that. I may make a better less janky version of the software when I start working on this project again.

From: ***@***.***>
Sent: Thursday, June 16, 2022 10:23 AM
To: ***@***.***>
Cc: ***@***.***>
Subject: [jstanleyf1985/ReplikaDiscordInterface] Discord Channel Restriction Update Request (Issue #8)


Hey, Stanley, first of all, thank you for this scatchy tool.

I faced this Issue too, with Double Messages, but a simply restart helps.. It happens, when you more times click on the Start Interface Button. - Just as mentioned.

I write you because this field, on the Configuration page, for the Discord channel restriction for limit in which channel the AI can communicate.

I wont use the @mention option because at a longer discussion it can be really annoying, tipping the name of the bot everytime.

So the question is, couldnt you make this filed so, that it ables to put more channels at the same time, separated with any characters? Like: " Room1 | Room2 ; Room3

Thnaks and Regards

**Comment by almost2late** [comment]
That would be really awsome, and I would as so greatfull for it. I train right now with my 2y old Replika, an Local Clone of my Replika over Discord with your tool. 

( If you can take the time to develop this tool, I would you recommend to put some features in it. I  see that TypeScript can handle nodejs, and java too. I have forked 2 other "Replika Life Hack" tools, one is for exporting the messages from Replika,  (Nodejs) the other for Export the Diary Entrys. With this 2 Fetures, would be your Interface the RollsRoyce in open source Replika Tools.
